server:
  port: ${PORT:8082}

spring:
  application:
    name: loyalty-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: loyalty-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.loyaltyservice.event.OrderCreatedEvent
